### ISSUE TITLE
This response is not simple text.Use the `result.parts` accessor or the full `result.candidates[index].content.parts` lookup instead.

### ISSUE THREAD

**Issue by whmc76** [ZHO-ZHO-ZHO/ComfyUI-Gemini#8]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini\GeminiAPINode.py", line 92, in generate_content
    textoutput = response.text
                 ^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_windows_portable\python_embeded\Lib\site-packages\google\generativeai\types\generation_types.py", line 328, in text
    raise ValueError(
ValueError: The `response.text` quick accessor only works for simple (single-`Part`) text responses. This response is not simple text.Use the `result.parts` accessor or the full `result.candidates[index].content.parts` lookup instead.

**Comment by jags111** [comment]
I am having same issue and any recommendations for same. Please advise.. or is some thing changed in the workflow when using the text prompt outputs

**Comment by whmc76** [comment]
Maybe it's because of the long input? I reduced the length of the input text and it can be used, but I still want to be unrestricted, after all, it seems that the api supports it.

> I am having same issue and any recommendations for same. Please advise.. or is some thing changed in the workflow when using the text prompt outputs

**Comment by jags111** [comment]
got it to work with changed input params or prompts

**Comment by OliverCrosby** [comment]
What did you have to change?

I wonder if the error is because sometimes gemini thinks you're asking it to generate an image, which it would do instead of returning with text.
